apiVersion: v1
kind: Secret
type: Opaque
data:
  fullchain.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURVRENDQWppZ0F3SUJBZ0lKQUxvbkp2RGR1RStHTUEwR0NTcUdTSWIzRFFFQkJRVUFNRm94Q3pBSkJnTlYKQkFZVEFsQk1NUk13RVFZRFZRUUlEQXBOWVd4dmNHOXNjMnRoTVE4d0RRWURWUVFIREFaTGNtRnJiM2N4SlRBagpCZ05WQkFvTUhFVnVkbTk1SUVOdmJuUnliMndnVW05dmRDQkJkWFJvYjNKcGRIa3dJQmNOTWpJeE1qRXpNRGt4Ck1UQTJXaGdQTWpJNU5qQTVNall3T1RFeE1EWmFNRDB4TGpBc0JnTlZCQU1NSldWamFHOHRjMlZ5ZG1WeUxtUmwKWm1GMWJIUXVjM1pqTG1Oc2RYTjBaWEl1Ykc5allXd3hDekFKQmdOVkJBWVRBbEJNTUlJQklqQU5CZ2txaGtpRwo5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBeTRLZzVsbitkU2hUL2M4aWJLakI1WjBnNVlOVTZMMXY1WWV2CjcrM0VzK0xMdm5yRHJLMlhsNi8xcEJoS3R4bGdrRTlYZVF4R013N1pOQnBTZE4vZmVmeFVHcEFSa1hUWUtUdnMKa2NDZWlLVGhPL25HQkdQaXUvOTluSDZLUXNoUWVkK08xSmdvYkRpdDVITDF2WFZmTTNIdUo5YXZpbFhQQVhTNQpzODJnZlQ5TUZzdXdsVnBKWTRPTkZqWm1uYjJDNVljcnVkeGgvTVhqanowdGhFSnlJcE40bWpaWWExTlJMZHg1CnF6WFgwZUg1WGtzdkVUUnl3QytKeFBDR0VlZ3JnOGhwcjhYWVc3QVpXWXBaMmdCdGlONEpMUldhcUxBemYyOW8KcFNYWURvbURsRTBlNDlodVQ2em5PRUFSMnEvb0diMU1uaENySGR1TXBDTDdOUUcydlFJREFRQUJvelF3TWpBdwpCZ05WSFJFRUtUQW5naVZsWTJodkxYTmxjblpsY2k1a1pXWmhkV3gwTG5OMll5NWpiSFZ6ZEdWeUxteHZZMkZzCk1BMEdDU3FHU0liM0RRRUJCUVVBQTRJQkFRQ0xOcFZOZzh1YnA1WEdWa2xWTGV6NXA1cnlPT0hNTi9VaDl3MysKNFlHT3NWZUlzMENIdmlZdStNVHFmait2ekMyaVZNT09ma0tmZkhqd3N2OHhpanBpbXR4Qzh0M29KQmR4Z09QUQpxRWNjeEIrbUNjOEpUajBtcG1EU2hOcWVBLytnOEprb2FvTkp5SGN4QUZRdUlyYVpjRDJESWtIN3ZKallnVkF2CmFJVjJNN0l5bHZmcHlkWmM4aWNzbDA4Szdlb0pDOXJVZXBGZ0dOdUV5OWI0cW91QXZvQmd4Ry9VQU05anFRcFMKV1RNNHFwTjFiTEgxZGxCMlo3L1hsNTZ1TDJRSEtQWEdiYjdFcFArMm14d0laQmxXaW5RUCtUdXdsTkV5Yk9NUQppZjVIT21pYlRiSnhFbFlFTyt0ME9GdEJVU28vMkY0UVhCRGh4NTBVc3ROam5mSW4KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  privkey.pem: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBeTRLZzVsbitkU2hUL2M4aWJLakI1WjBnNVlOVTZMMXY1WWV2NyszRXMrTEx2bnJECnJLMlhsNi8xcEJoS3R4bGdrRTlYZVF4R013N1pOQnBTZE4vZmVmeFVHcEFSa1hUWUtUdnNrY0NlaUtUaE8vbkcKQkdQaXUvOTluSDZLUXNoUWVkK08xSmdvYkRpdDVITDF2WFZmTTNIdUo5YXZpbFhQQVhTNXM4MmdmVDlNRnN1dwpsVnBKWTRPTkZqWm1uYjJDNVljcnVkeGgvTVhqanowdGhFSnlJcE40bWpaWWExTlJMZHg1cXpYWDBlSDVYa3N2CkVUUnl3QytKeFBDR0VlZ3JnOGhwcjhYWVc3QVpXWXBaMmdCdGlONEpMUldhcUxBemYyOW9wU1hZRG9tRGxFMGUKNDlodVQ2em5PRUFSMnEvb0diMU1uaENySGR1TXBDTDdOUUcydlFJREFRQUJBb0lCQUJWSytKekJZNzlNVmVWagphNzJrdG96WXNOMXlyVXFncjNsN2hldjdtNjRhbDZpNVhZbk9xK0xDRlZoeTlqWk1JRzlZN2RVTGRMalkzOTcwCnRoWG1hcEp2MVRqbVJBQk5FbVRXRVQxNnd0dVhMTDNDdDNZMElULzhUbDgyV2k3OG1IYjM3aERPVHNScjliM0cKVFhIaU92QytCZVlETDJDdzg3UzZTc2ZHUnZsem15dEdwL3hBa3ZEcUd4Z3FFbGNIclg5Q0czdm5DMTY4Q0NoagpSY2Z6L2RDLzJlY29NV1FZMEVjL2d5bzBaTVQ2TzZZVW5nZG9nRUg3eTB4QVBRd2ZxNWVCaUFqUTJMYTJOZjZoCkxMbmtzOFl2dGVEMEl4WVhEbnlhYlBxMEIrNURFcmFERnBnY1JobGZTL1dJcUM5bktoMHBSVXRlOWJ0dzN2Rk8KcDYxRyt4MENnWUVBN2Y2b05Ld1NOL25mbllqaHlCbWNMRU1JWHhOM01PQUg4OTdxaWEwZFJhMGJqYjdQYlMyQwpEZDdBL0Nqa1E2cURFcGQ1a0VmYVNiZTBRZDRyem82b09jVS84RWZabzBOS09mZXozaEJ1djhNUWVlWXJMYjBkCmdkaW1adG1kMjVXZS9hYm0rK3ppMWMzSm9DRllXaWZSSG5MUGZFb21OVWlwOVVUa2d4VGdrZk1DZ1lFQTJ1Z1kKbkN2ZFhDTW0zYnZPS1FXYXNTS1E2b1JUckFaQWRkb1ZaOStYV1pzQWJJU2lUQW02akw0dkptRytFcGN2c0JJSgpnVjNGMkNZOEkyeWc1dno0TXVLK0dtbzk2WGtQQzE0aXEwK29QYk1udUJpQ1F3WFoxTXVzcjU0cmZHZkhsRkVECmlJR01hdStGOTZZWWhoUldLYk5ZeTl4djdRYVFjV1dIK3c4TEVJOENnWUVBNXBnR1REcW8wRm1vQTVCY0N6QmQKTkRtaXc5UXRlVXFvQ2U5ajJnL0V1L3oxSklyTG1lSXREOWxUclQ3RnBKWnl0ekhURkN1NlloQy9jODZiTFdEbAp1RXZaSHF2UFFMUHpHR1ZiZm43M2Y0KzF5Qlp1b2J1SitvUjYvazQ5K0VOcE1DVmx5cFNFV0ZveTBKZGVic1FECmgzZ0FkMUcwNFkzTk54c1FPYjJodFdjQ2dZQnpzY2tYK1FMMEtFdnBVdEhoMG1sd2h4RktNUWU3Mms0Rk8yNm0KeUlCSVJtaVI4Z09JNW5kbTNUazBNdUp2RnVLSVR2QWhKRHRsUXNmei9QeUpPRmZCSlI5Ti9LcWVFM0pGRXNxRgorZ0swSVZTenNwaGQ3ZUN6MjdWMzE4T3A2M3VLd3NwNFFlZkJ1TGY0TEJ1MytWV1Vrb295ckYyblN4bmFKTXdhCmYxZmN0d0tCZ1FEaFNVV2tTcGVSOFNKN3doV2gxRGdiZWNGV1dlNHJCMFZ6T25wZTdKK0haOXlRUDc2eFhkclEKemtZbDYvTkV2SkNleVUxcWhnOEpib3JuMDdNV0w3Q1I1ZGQ1Z1V1SHFCQjhhb2gzcWdxaWsyZlJXOWdwM1g0agp2dll3UlViWEZjNGg4QnNvYU9yVzI3MnQvVlNHaUgrMFJtNXdZMElOTmRRY2N4OUxSakFuR2c9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
metadata:
 name: echo-tls
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: echo-server
  template:
    metadata:
      labels:
        run: echo-server
    spec:
      containers:
      - name: echo-server
        image: mendhak/http-https-echo:26
        volumeMounts:
        - name: certs
          mountPath: /app/privkey.pem
          subPath: privkey.pem
        - name: certs
          mountPath: /app/fullchain.pem
          subPath: fullchain.pem
      volumes:
      - name: certs
        secret:
          secretName: echo-tls
          items:
           - key: fullchain.pem
             path: fullchain.pem
           - key: privkey.pem
             path: privkey.pem
---
apiVersion: v1
kind: Service
metadata:
  name: echo-server
  namespace: default
spec:
  ports:
  - name: http
    appProtocol: http
    port: 8080
    targetPort: 8080
  - name: https
    appProtocol: http
    port: 8443
    targetPort: 8443
  selector:
    run: echo-server
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Namespace
metadata:
  name: es-test
  annotations:
    kuma.io/sidecar-injection: "enabled"
---
apiVersion: kuma.io/v1alpha1
kind: ExternalService
mesh: default
metadata:
  name: echo-server
spec:
  tags:
    kuma.io/service: echo-server
    kuma.io/protocol: http # optional, one of http, http2, tcp, grpc, kafka
  networking:
    address: echo-server.default.svc.cluster.local:8443
    tls: # optional
      enabled: true
      allowRenegotiation: false
      caCert: # one of inline, inlineString, secret
        inline: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURNakNDQWhvQ0NRQ2szL1JsRjNqWXBqQU5CZ2txaGtpRzl3MEJBUXNGQURCYU1Rc3dDUVlEVlFRR0V3SlEKVERFVE1CRUdBMVVFQ0F3S1RXRnNiM0J2YkhOcllURVBNQTBHQTFVRUJ3d0dTM0poYTI5M01TVXdJd1lEVlFRSwpEQnhGYm5admVTQkRiMjUwY205c0lGSnZiM1FnUVhWMGFHOXlhWFI1TUNBWERUSXlNVEl4TXpBNE5ERTBNbG9ZCkR6SXlPVFl3T1RJMk1EZzBNVFF5V2pCYU1Rc3dDUVlEVlFRR0V3SlFUREVUTUJFR0ExVUVDQXdLVFdGc2IzQnYKYkhOcllURVBNQTBHQTFVRUJ3d0dTM0poYTI5M01TVXdJd1lEVlFRS0RCeEZiblp2ZVNCRGIyNTBjbTlzSUZKdgpiM1FnUVhWMGFHOXlhWFI1TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF5VVpJCnhhWHdLd2YwT0lTanN0dm81UmREbkxQK2ZzbndiNmdQeVVzK3JRNThyenlrQ20rYkt3NkxuTVBQcklVa1BUZ3kKTGc1dzJVZXZKVnVSS2FHSXBid2JDRHc5VVNDcXpKaFpyL1c2a1NxNnB3dWliNEYzM0xvbFQxeHJ5QU1vMEhHLwpERURDY1dMUy8xRERyMmRKVkpYMEtXZTBWVEhBZVltS0U2SUgrMVA0MGNZVUlBemppN1BNcktoQXM3SWI2aEhOCkZwZXJyc0t0Q0t1WUFaTEczcGtBTlJuRDczdXZXeitIL210WXBldGFJZFUrT0FoRm8vSTVaaDlnaDc3RElNZFEKU1ZMekhkV2c1VkU4aml2MmtwTVVuV3JRZjE2WFhCaXQ5bVp2U2lZaHY1REhUTXFlWGF2MU5NbUY4K2ZsRlozcgp3UGRvSXZJbkxxbWJ5YXBWM1FJREFRQUJNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUFjS2g0OS9heCt1NHVtCjJqUWpSeWEwOW9yLzZVSnUrK3NJN0ZWblVQQ09Kc1ZhUFYxcEV4L1N2eUFvdVpYWC9ObzRUZWdjdmtIUGNzaUsKZmxNbG9LUFphOVVtd3lCcGRZRUs1VC9STVZhbXdiMmhMSGo0YjdjV3AvUVVjN0dsbFVSRXR0bFNUWDFzNEwxaQo1MEJLNVRoaE9ScFRqOE8yMklMUGZHNE85MzNhMkRhUjAzRW0rLzF3VnlTNVFZREc4NmhmaGFUemNCMGtLMXN4Cmt3K2lKL1YzckZGTmN2dVRyRzYrOEg3TmdOVDBkS0VkZkUyenBwTEdhOG5Id09GTnZ2b1pJUkJTa3pTckxqNWMKaldnMGxpb3o4MGtlSUExVG04T0VNaXlUaDhjM3Z4Z3Y1eE9UdjViRDhFM2NCanNsNG91MHdtUkxMT2xlQkhtVQpPUnJLUHRpLwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      clientCert: # one of inline, inlineString, secret
        inline: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURPVENDQWlHZ0F3SUJBZ0lKQUxvbkp2RGR1RStGTUEwR0NTcUdTSWIzRFFFQkJRVUFNRm94Q3pBSkJnTlYKQkFZVEFsQk1NUk13RVFZRFZRUUlEQXBOWVd4dmNHOXNjMnRoTVE4d0RRWURWUVFIREFaTGNtRnJiM2N4SlRBagpCZ05WQkFvTUhFVnVkbTk1SUVOdmJuUnliMndnVW05dmRDQkJkWFJvYjNKcGRIa3dJQmNOTWpJeE1qRXpNRGcwCk5EUXpXaGdQTWpJNU5qQTVNall3T0RRME5ETmFNRDB4TGpBc0JnTlZCQU1NSldWamFHOHRZMnhwWlc1MExtUmwKWm1GMWJIUXVjM1pqTG1Oc2RYTjBaWEl1Ykc5allXd3hDekFKQmdOVkJBWVRBbEJNTUlJQklqQU5CZ2txaGtpRwo5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBdnNjdWdSbEhSbmNOcFRHSTNqUStaMDJVakVVamIwVFhZMGhYClZSU2ZLd0hxVW5OUUw0YjVuenVTVjFvc3BxMU5malY4TnpLQUNMS25yQlE4cFZkV3BBWUVSQmtncjN0VjB3eG4KSzlqdEdHUE9hSkY2N1lYQytTTkd6RFFyUXdnOXlxZDlpeDYxd2lKeDNRTERnNjcxdUdDcXJkRGZpbjh4RnN5MQoyVzdCdFVQaDRpS2VpVjZaSm5OdVB1bkpndXg2S2NwaVBBR0dhSlRWVS9HSE54ckFDZTJQTzcxNWwvQm9sVXZFCm1OVCthRlA4WFEvSmYyTy9sN2xjd21sYWIrOEsyTk9seDlPOVQ0eUNsNTVabHVsRVhZYWJTdjdGZ0R3a1RDUkwKbUZyWUpqUGJjYmhTaUthdjJGcTBQcXlQNUdzY01RRUxaU245blNyVnVTalZhVU9NcXdJREFRQUJveDB3R3pBWgpCZ05WSFJFRUVqQVFoZzV6Y0dsbVptVTZMeTlsWTJodk1qQU5CZ2txaGtpRzl3MEJBUVVGQUFPQ0FRRUFIN1FZCnN0WUdSRzU1WjQxdEUyb25VbWNqa2VzeWhHd3J1ZXhTbDJOb0czQ05MK2UvaC9uT1FzNFdZWWkxOHg3aU1yMksKSXNGUDBoUnoyNmFkYm9sdEFBWkRqSElKUEQ1V2tTSlVPbHRQNzAwYURhblNHUFRHVjZ6VzZGUTROTCtwb01HVQo5dXlnaXllOEh4ck9veWNyandLU1BrUG9ibTRYY2duc2hIdHF6QjJ0K0VVckFJVlhaYUJCU2tlTDNFeWlqTWxqCmNJYWEzUDR4N3FFd1ZMZXpneklTNHRpaG1pN01Nczc4NWFYUlZlZkN2OWJJYWc3cDRPeEJEK2x2U0tsV21pVzYKVmxUS1F3b3cyN2d4ZVFmWEd0cE1DaXU1RFlFTFNwc1pFVmptZVJvdjc0SUowTHFQaHhhY09jZUZPbEFlTXk1bApyL1VvVCtDWHJ0bStXZUtUbVE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      clientKey: # one of inline, inlineString, secret
        inline: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBdnNjdWdSbEhSbmNOcFRHSTNqUStaMDJVakVVamIwVFhZMGhYVlJTZkt3SHFVbk5RCkw0YjVuenVTVjFvc3BxMU5malY4TnpLQUNMS25yQlE4cFZkV3BBWUVSQmtncjN0VjB3eG5LOWp0R0dQT2FKRjYKN1lYQytTTkd6RFFyUXdnOXlxZDlpeDYxd2lKeDNRTERnNjcxdUdDcXJkRGZpbjh4RnN5MTJXN0J0VVBoNGlLZQppVjZaSm5OdVB1bkpndXg2S2NwaVBBR0dhSlRWVS9HSE54ckFDZTJQTzcxNWwvQm9sVXZFbU5UK2FGUDhYUS9KCmYyTy9sN2xjd21sYWIrOEsyTk9seDlPOVQ0eUNsNTVabHVsRVhZYWJTdjdGZ0R3a1RDUkxtRnJZSmpQYmNiaFMKaUthdjJGcTBQcXlQNUdzY01RRUxaU245blNyVnVTalZhVU9NcXdJREFRQUJBb0lCQVFDaWpOUHk2N2J2TTBGTgpINGVlektUZklCc1I2VmJuMTZBdDE5V1JpS0NWNUd2akZKMmQ0VU9QaVJLSG15MndWcmxRY0FJR2hlRFJpR2VWCkZ5a1ZOL1Y2akNYV1lCS1pjbDBPRmVOU1dPS3JoVjY1ZWp0alpqVmFVZFJnNlpKeTZ2SzdXVHArN3d1dS9lcEcKaGJSUTN5SStseDdXT3NJOUgyS1VLcGhIU3plQldYcDR4SzJoSmRjVFRQUWo3b2IyaGQ5dE9IK24vbVZ0ZncxLwowYXU0eTI5RnAyVUtRZ1dhaXZxSk5TM2Fvcm1CeHZKc3k0TmdVWnRCQ1JFUUFZWXBHeTVvN3VIRy9vSmY0allUCnFoT3dlWUZCRHcySHEzSE1DUjF2QVlBYkZZTFd0QjlvZCt2MDhadmdraFZiS3FENnhIbXBpUkFLa25qVU5TUm8KbFVzTHFUd0JBb0dCQVBlQUN2bFNFbHhBMzFFVHZ1dDFHMjdxWlVORlg3bFJkM00xeXZ1eTIzaVhlczVPMU44QwpOWkRmOG9rOUFIRzlwOHRrVDVyUDR4OTlVaXRiL1Zpdm91RWxFSWpudzFBMEpyd0RQVjRaWUFLNG1COHd3eHQxCklNWitLN0o4YVYxV2VjZXBTQzF0dFEyRDdDcTBTRUxEdUdpbURCVlJsczJoK0t0bkVURC92Qm14QW9HQkFNVlUKYytTMlp0TzlxQWdjeHpSd293WlJuNWpmZGlzUzF2emxocnNBUU5zWnZBNlpHNVdjMTZXVzZKcC9aMDhIcm5JcQpNeC8xK0taNUFnZkVoVzZPdElKTEJ2endvL2ZscnJ2cW8vNG44bHpQUVNqUkR6NGJqNmowSG9aK1NIdzQ5S2hwCkhxRk9KN0RxdllLN1BwMmsycWg1eDZpc1NIL0NFRTl5aXdKTWlRY2JBb0dBWFc0MHRsSEpKSkpJdXk2ZEQvMngKVVhtaXFIWno0RjFrbmxWY1B4QVIwY0E5Vjh4aWg1MHA0M3JtNysvYlR4U3RWeGFUQm5vYjN6Tkw1WnBnVlM1WQphbTIzaERjWmdCbHYxZUhUTk1hWGUrOTdYYXJtdkdMRzhLZUlqMlJ2MGhCbkFIeGpCdU0zU2RiWFBIZTZINW9LCjcxWmZrVnl2ZFFrRCtwQjU2T2xoZE1FQ2dZQXZOa1dFTXgvbkNUbHF0M2Z4MUFFdFFkb3RlVW1NaExWclRIOHYKdnAvRnpDSnlXNjk5M0VpOEZaOFJWK29mdm5hK1dkcGhpemd5bkVFZ0dxVFNEdEtoV2RJU01vRUlqcXQveW1QeQpLeHlSbUFTKy8wWG1WakhJK3A5VERtUEpWTmMwYy9JZ0pkTFpRVkNXTnJhRWdTelBvbE5peDlXUXU1MnJaSHhkCjBISDRnUUtCZ0N2ZEd2cCs4SUdhRGJ0THUrQ085OVRxVlhIdGJwTnFjbG8zanJHSm5IczRvK2FOTUgzdDljQ3MKNEJucmxtMi9ycHN5L21UUzVSZkVGNTZvYzJWYkI0MktJRTBuL2tQbFpDak00Vms1UzhyVVlwN3d2Rm1FUW1zVAp2TndCZmhPcDZHd2dTMTg1dmUzdVd2eTM4YThTeUdxWUNxSm1XdmJEeDNCcDQ5eWQ4S3l0Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
---
apiVersion: kuma.io/v1alpha1
kind: ExternalService
mesh: default
metadata:
  name: echo-server-plain
spec:
  tags:
    kuma.io/service: echo-server-plain
    kuma.io/protocol: http # optional, one of http, http2, tcp, grpc, kafka
  networking:
    address: echo-server.default.svc.cluster.local:8080
